### ISSUE TITLE
Cater for existing de-facto ontology metadata model properties

### ISSUE THREAD

**Issue by nicholascar** [FAIR-IMPACT/MOD#10]
[LODE](http://www.essepuntato.it/lode) uses properties like `rdfs:label` and `rdfs:comment`. These should be catered for either by either being specifically allowed or specifically deprecated ("use `dct:title`"). 

A list of LODE properties not in MOD:

* rdfs:label (for the ontology)
* rdf:comment (for the ontology)
* dc:creator and other direct agent expressions
    * as a Literal for the ontology, as opposed to a BNode or URI-defined foaf:Agent

*more to come when I inspect LODE carefully!*

**Comment by jonquet** [comment]
Never too late to fix issues ;)

- Indeed "rdfs:label" for mod:SemanticArtefact was in the description text, in the GSheet but not fomally in the source file! Good catch.
- rdfs:comment was there for a while, and its consider a "selected" property (https://github.com/FAIR-IMPACT/MOD/blob/main/mod.ttl#L919)
- For agent... we shall take care of this in #9
