### ISSUE TITLE
Alignment with DCAT 1.1

### ISSUE THREAD

**Issue by nicholascar** [FAIR-IMPACT/MOD#12]
This is not an issue to be solved instantaneously so this issue is a place to discuss alignment.

Alignment will rely on both the stability of the next DCAT release (approx 6 months) and the results of an investigation into the appropriateness of DCAT 1.1 elements for ontologies.

**Comment by smrgeoinfo** [comment]
see in particular the work on a dcat profile for datasets, which I think will have significant overlap with metadata required for ontologies
https://github.com/w3c/dxwg/tree/dcat-profile-research-data/dcat

**Comment by jonquet** [comment]
Thanks for your input guys. 

We have to review new version of DCAT here: https://www.w3.org/TR/vocab-dcat-2/
@biswanathdutta what do you think ? 

Then we have to released MOD1.4 (not DCAT compliant but more complete than MOD1.2) then we will have to start working on MOD2.0 (DCAT compliant).

**Comment by jonquet** [comment]
DCAT2 compliance was achieved with MOD2. Indeed that was desired by many and discussed in multiple occasion during FAIRsFAIR project.
