### ISSUE TITLE
Separate implementations from ontology defintion

### ISSUE THREAD

**Issue by nicholascar** [FAIR-IMPACT/MOD#14]
In the latest copy of the ontology document, [mod-v1.2.3_with-instances.owl](https://github.com/sifrproject/MOD-Ontology/blob/master/versions/mod-v1.2.3_with-instances.owl), instances and the ontology definition are both present. Recommend maintaining a 'clean' ontology latest version as mod.ttl (no version in file name) in the root of the repo and separate, individual, implementation files in an implementations/ folder.

**Comment by jonquet** [comment]
Indeed, this file from v1.2.3 was an experiment to "represent" multiple ontologies as instances within MOD. Alike doing a knowledge base.

Now the file is indeed mod.owl only, and contains the schema only.
