### ISSUE TITLE
Upload MOD ontology to LOV

### ISSUE THREAD

**Issue by nicholascar** [FAIR-IMPACT/MOD#21]
Upload MOD to http://lov.okfn.org/dataset/lov/ for visibility.

**Comment by jonquet** [comment]
This would be indeed relevant. Still... we have not done it all these years kind of waiting for the "right" OntoPortal-based repository to host MOD... 
Originally BiblioPortal was supposed to take it, but the project stoped. 
We are now discussing porting LOV to OntoPortal too (LovPortal). When done we shall put MOD (and its version there for sure).
