### ISSUE TITLE
Use of MOD ontology to describe an existing ontology

### ISSUE THREAD

**Issue by marcosabda** [FAIR-IMPACT/MOD#22]
Hi, we would like to know how it is possible to use the MOD ontology to describe an existing ontology. One idea we considered is to use the MOD properties as annotation properties in our ontology. Would this make sense? Do you have any other ideas?
Thank you.
Marco

**Comment by jonquet** [comment]
Hi, Yes you can do this (annotation properties). 
Teh current version is 1.4 see the profile in the branch:
 https://github.com/sifrproject/MOD-Ontology/blob/mod-1.4/mod-1.4-profile.rdfs

It shows how to use annotation properties and copy/paste the properties you would like to use in your ontology.

**Comment by marcosabda** [comment]
Dear Jonquet,

Thank you very much. I will look into it soon.

Best regards,
Marco
______________________________________________________________
Dr Marco Cinelli
Marie Curie Global Research Fellow

(Current location) U.S. Environmental Protection Agency
National Risk Management Research Laboratory (NRMRL), Cincinnati, OH, USA

Laboratory of Intelligent Decision Support Systems
Poznań University of Technology, Poznań, Poland

Guest Teacher
Department of Management
London School of Economics and Political Science, UK

-
@: marco86.posta@gmail.com 
-
My website <https://sites.google.com/view/marcocinelli>  |  Google Scholar profile <https://scholar.google.com/citations?user=UrnXLb8AAAAJ&hl=en>  |  LinkedIn profile <https://www.linkedin.com/in/macinelli/>
