### ISSUE TITLE
values typed xsd:dateTime are not valid

### ISSUE THREAD

**Issue by smrgeoinfo** [FAIR-IMPACT/MOD#39]
in mod-v2.0_ontology.owl 
"2015-08-05"^^xsd:dateTime ;
gets warning from topBraidComposer
"Lexical form '2015-08-05' not valid for datatype XSD dateTime."

Not breaking, but why not fix and make them xsd:date?

**Comment by jonquet** [comment]
Assigning @biswanathdutta as he is the person that have produced the mod-v2.0_ontology.owl

**Comment by biswanathdutta** [comment]
@jonquet @smrgeoinfo removed the bugs, thanks for pointing to that.

**Comment by biswanathdutta** [comment]
Dear Clement,
        I have corrected it. Also, made a pull request.
The request is in wait for reviewer approval.

Regards,
Biswanath
