### ISSUE TITLE
Use owl:equivalentProperty to define ALL properties in mod namespace

### ISSUE THREAD

**Issue by jonquet** [FAIR-IMPACT/MOD#4]
If we want someone to concretely use OntoLOD (the Linked Data of Ontologies) for instance thru SPARQL query, he/she will shall not have to know all the namespaces and selected propery in MOD. 
Therefore, I would suggest to use owl:equivalentPropery to define ALL properties of MOD within the mod namespace. 
Then in a SPARQL query, someone can either use for instance dc:creator or omv:creator. This will be the same property within MOD.

**Comment by biswanathdutta** [comment]
Hi Clement,
    Sure, we can look into this possibility.
However, we need to look into the other consequences of this. For instance,
in terms of verboseness, and semantic implications.

With regards,
Biswanath

**Comment by jonquet** [comment]
Hi Biswanath,

Indeed there will be a bit more statements (verbose) but at usage it shall be more convenient for someone to just declare one ns and only use the name of properties. 

Semantic implication of owl:equivalentPtoperty is quite simple. Locally the 2 properties are considered the same and can be called independently. 

Feel free to follow up on github tracker. This will help us memorize the decisions and also make all of this public. Which shall be important if we claim becoming a referenced standard. 

Bye
Clement Jonquet 
Assistant Professor, Univ of Montpellier, Visiting  scholar at Stanford univ.

**Comment by jonquet** [comment]
This is still doable. But I think that after all this time if it was not necessary, we can close and avoid to do it.
