### ISSUE TITLE
:SemanticArtefact class not defined

### ISSUE THREAD

**Issue by smrgeoinfo** [FAIR-IMPACT/MOD#40]
in mod-v2.0_ontology.owl, there are the following statements, but no declaration of :SemanticArtefact. I assume its' supposed to be mod:SemanticArtefact.  This is breaking.   ?maybe mod-v2.0_ontology.owl is deprecated???

line 3045:
### https://w3id.org/mod#Taxonomy
mod:Taxonomy rdf:type owl:Class ;
          rdfs:subClassOf :SemanticArtefact .

### https://w3id.org/mod#Terminology
mod:Terminology rdf:type owl:Class ;
             rdfs:subClassOf :SemanticArtefact .

**Comment by agbeltran** [comment]
Thanks @smrgeoinfo for spotting that. You are right - we're revising MOD as part of the FAIR-IMPACT project and we will make sure to fix this (we are working for version MOD 2.1)

This is the link to the line you refer to:
https://github.com/FAIR-IMPACT/MOD/blob/8a27405be5dbf19e4ea1a2b1a3c25c4d6615c55e/mod-v2.0_ontology.owl#L3045

Can I also point you to the design decisions discussions? https://github.com/FAIR-IMPACT/MOD/discussions

It would be great to get your views.

**Comment by jonquet** [comment]
Assigning @biswanathdutta as he is the person that have produced the mod-v2.0_ontology.owl

I do confirm @agbeltran 's point on the fact that we are re-taking all of this in v2.1

**Comment by biswanathdutta** [comment]
> in mod-v2.0_ontology.owl, there are the following statements, but no declaration of :SemanticArtefact. I assume its' supposed to be mod:SemanticArtefact. This is breaking. ?maybe mod-v2.0_ontology.owl is deprecated???
> 

@smrgeoinfo Yes, it is mod:SemanticArtefact. 
See here https://w3id.org/mod#SemanticArtefact

**Comment by agbeltran** [comment]
thanks @biswanathdutta @jonquet 

but the problem that was raised was that the SemanticArtefact class was not defined in version 2.0

I've now created a pull request to resolve this issue, and of course, we will keep it and add more details in 3.0

**Comment by agbeltran** [comment]
This issue has been fixed in https://github.com/FAIR-IMPACT/MOD/pull/55 - and the SemanticArtefact class and definition will also be available for version 3.0
