### ISSUE TITLE
Define mod:SemanticArtefact as a subclass of dcat:Resource

### ISSUE THREAD

**Issue by agbeltran** [FAIR-IMPACT/MOD#44]
As per discussion on the first design issue (https://github.com/FAIR-IMPACT/MOD/discussions/34), considering MOD as a DCAT-Profile, we will define ```mode:SemanticArtefact``` as a subclass of ```dcat:Dataset```

```
mod:SemanticArtefact
  a rdfs:Class ;
  a owl:Class ;
  rdfs:subClassOf dcat:Dataset ;
```

**Comment by agbeltran** [comment]
Further to discussions which are summarised in https://github.com/FAIR-IMPACT/MOD/discussions/34, we will derive ```mod:SemanticArtefact``` from ```dcat:Resource```

```
mod:SemanticArtefact
  a rdfs:Class ;
  a owl:Class ;
  rdfs:subClassOf dcat:Resource ;
```

**Comment by jonquet** [comment]
Closing as this was done in v3.0
