### ISSUE TITLE
Add schema.org creativeWorkStatus as a mapping for mod:status

### ISSUE THREAD

**Issue by jonquet** [FAIR-IMPACT/MOD#57]
https://schema.org/creativeWorkStatus

**Comment by jonquet** [comment]
Done in https://github.com/FAIR-IMPACT/MOD/commit/e7bcdd0aa22f01527fb070c29da4ca4f1d5715ad

@antony-wilson I leave it open so you could update the MOD-mappings repo content with this new mapping.
Please close the issue after.

**Comment by antony-wilson** [comment]
The mappings have been updated. https://github.com/FAIR-IMPACT/MOD-mappings/commit/72fc4a8a95cc2c462e8f5ffd862c9a69a13aa834
