### ISSUE TITLE
Class names should be capitalised

### ISSUE THREAD

**Issue by antony-wilson** [FAIR-IMPACT/MOD#66]
A number of classes in the ontology do not have a `rdfs:label`, this results in them being displayed with lower case names.

Classes requiring `rdfs:label`:

- [x] - SemanticArtefactCatalogRecord
- [x] - SemanticArtefactService
- [x] - SemanticArtfeactCatalog
- [x] - Taxonomy
- [x] - Terminology
- [x] - Thesaurus

**Comment by jonquet** [comment]
Addressed in v3.1
