### ISSUE TITLE
mod:toDoList in mod.ttl points to a URL that returns 404

### ISSUE THREAD

**Issue by antony-wilson** [FAIR-IMPACT/MOD#71]
mod:toDoList points to https://github.com/sifrproject/MOD-Ontology/raw/master/mod-v2.0_todos.txt

This link returns a 404

**Comment by jonquet** [comment]
Could be updated to https://github.com/FAIR-IMPACT/MOD/blob/main/mod-v2.0_todos.txt 
But may need to make it version agnostic and of course update the content according to recent work.

**Comment by antony-wilson** [comment]
How about having a GitHub project for TODOs?

**Comment by jonquet** [comment]
You mean use the project features of a GitHub repo? (not creating another repo I guess)

**Comment by jonquet** [comment]
Just moved all the TODOs within specific issues yesterday and archived the old todo file to the version folder (after rmeonving from the file the things moved to issues)
